AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An Amazon SNS trigger that logs the message pushed to the SNS topic.
Resources:
  requestQueue:
    Type: AWS::SQS::Queue
    Properties: 
      VisibilityTimeout: !Ref LambdaTimeout
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap 
        - OperationsMap
        - OutputBucketMap
        - !Ref Environment
  OutputBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref OutputBucket
      PolicyDocument:
        Statement:
          - Action:
              - s3:PutObject
              - s3:PutObjectAcl
            Effect: Allow
            Principal:
              AWS: !Ref MediaRole
            Resource:
              Fn::Sub:
                - arn:aws:s3:::${Bucket}/*
                - Bucket:
                    !Ref OutputBucket
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ws-dazzler-copy-media
      Handler: index.handler
      Runtime: nodejs12.x
      InlineCode: exports.handler = function(event,context){}
      Description: An Amazon SNS trigger that logs the message pushed to the SNS topic.
      MemorySize: !Ref LambdaMemorySize
      Timeout: !Ref LambdaTimeout
      Events:
        MediaSyndication:
          Type: SNS
          Properties:
            Topic: !FindInMap 
              - OperationsMap
              - MediaSyndicationTopicMap
              - !Ref Environment
        requests:
          Type: SQS
          Properties:
            Queue: !GetAtt requestQueue.Arn
            BatchSize: 1
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue:
              !Sub "${CoreInfrastructureStackName}-PrivateSubnet0"
          - Fn::ImportValue:
              !Sub "${CoreInfrastructureStackName}-PrivateSubnet1"
          - Fn::ImportValue:
              !Sub "${CoreInfrastructureStackName}-PrivateSubnet2"
        SecurityGroupIds:
          - !ImportValue
            'Fn::Join':
              - '-'
              -  - !FindInMap
                   - OperationsMap
                   - SecurityGroupStackMap
                   - !Ref Environment
                 - WsAppwMergeIsiteSgId
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref InputBucket
        - S3CrudPolicy:
            BucketName: !Ref OutputBucket
        - Statement:
            - Action: sts:AssumeRole
              Effect: Allow
              Resource: [ !Ref APPWRole, !Ref MediaRole ]
        - ElasticsearchHttpPostPolicy:
            DomainName: !FindInMap
              - OperationsMap
              - ESHostMap
              - !Ref Environment
      Environment:
        Variables:
          APPW_ROLE: !Ref APPWRole
          MEDIA_ROLE: !Ref MediaRole
          APPW_BUCKET: !Ref APPWBucket
          APPW_KEY_PREFIX: !Ref APPWKeyPrefix
          APPW_ENV: !Ref Environment
          DDB_TABLE: !Ref DynamoDbTable
          OUTPUT_BUCKET: !Ref OutputBucket
          EPISODE_PROFILE_ID: !Ref WantedEpisodeProfileId
          CLIP_PROFILE_ID: !Ref WantedClipProfileId
          COPY_TO: ""
          ES_HOST: !FindInMap
            - OperationsMap
            - ESHostMap
            - !Ref Environment
          MS_API_KEY: !Ref MediaSyndicationApiKey
  AliasForLambda:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionVersion: $LATEST
      FunctionName: !Ref Lambda
      Name: !Ref Environment
Parameters:
  CoreInfrastructureStackName:
    Default: core-infrastructure
    Type: String
    Description: >-
      Name of the AWS account's core-infrastructure stack. Used to import other
      network parameters (vpc id, subnets etc.)
  Environment:
    Default: test
    Type: String
    Description: The deployment environment
    ConstraintDescription: must be test or live
    AllowedValues:
      - live
      - test
  LambdaTimeout:
    Default: 30
    Type: Number
    Description: 'The function execution time (in seconds) after which Lambda terminates
      the function. '
  LambdaMemorySize:
    Default: 128
    Type: Number
    Description: The amount of memory, in MB, that is allocated to your Lambda function.
  APPWRole:
    Default: arn:aws:iam::746161738563:role/client-access-appw-cd-live
    Type: String
  APPWBucket:
    Default: public-bf7ec4ef6829c416
    Type: String
  APPWKeyPrefix:
    Default: programme_availability_cd/live
    Type: String
  DynamoDbTable:
    Type: String
    Default: dazzler-test
  InputBucket:
    Type: String
    Default: livemodavdistributionresources-distributionbucket-182btg2y28f33
  MediaRole:
    Type: String
    Default: arn:aws:iam::240129357028:role/LiveModavWspPublicStaticB-WspPublicStaticBucketAcc-L33J2E0BB6DT
  WantedEpisodeProfileId:
    Type: String
    Default: pips-map_id-av_pv13_pa4
  WantedClipProfileId:
    Type: String
    Default: pips-map_id-av_pv10_pa4
  MediaSyndicationApiKey:
    Type: String
    Description: media syndication API Key
Mappings:
  OperationsMap:
    OutputBucketMap:
      test: ws-dazzler-assets-test
      live: ws-dazzler-assets
    MediaSyndicationTopicMap:
      test: arn:aws:sns:eu-west-1:576677253489:test-ms-api
      live: arn:aws:sns:eu-west-1:294595276257:LiveMsdrPercolatorWorldServicePartnersResources-NotificationsTopic-10ZP19CXN5F82
    ESHostMap:
      test: vpc-test-pws-es-01-ntq5eu3xhbkw56fc2yi4vt2ndm.eu-west-1.es.amazonaws.com
      live: vpc-live-pws-es-01-sharq3wijppafqfq2v3isa5ram.eu-west-1.es.amazonaws.com
    SecurityGroupStackMap:
      test: test-ws-partners-core-SecurityGroupStack-CIWZAD831WU2
      live: live-ws-partners-core-SecurityGroupStack-SYT5JIU2MUSV
